# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.

terraform {
  required_version = "~>0.13.0"
  required_providers {
    bigip = {
      source = "F5Networks/bigip"
    }
  }
  backend "consul" {
    address = "13.125.63.212:8500"
    gzip    = true
    path    = "tf-state"
    scheme  = "http"
  }
}

provider "bigip" {
  address  = var.bigip.address
  password = var.bigip.password
  username = var.bigip.username
}

# Create AS3 Applications
module "AS3" {
  source   = "f5devcentral/app-consul-sync-nia/bigip"
  version  = "0.1.2"
  services = var.services

  tenant_name = var.tenant_name
}
